# Schema for the configuration files of the Tracking Number module.

field.formatter.settings.tracking_number_link:
  type: mapping
  label: 'Tracking number link display format settings'
  mapping:
    new_window:
      type: boolean
      label: 'Open link in new window'
    type_display:
      type: boolean
      label: 'Display the type'

field.formatter.settings.tracking_number_plain:
  type: mapping
  label: 'Tracking number link display format settings'
  mapping:
    type_display:
      type: boolean
      label: 'Display the type'
